version: "3.9"

services:
  api:
    build: .
    container_name: violt_core_api
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
